version: "3.8"

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  backend:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://cache
